# Generated by Django 3.1.3 on 2020-11-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Mindlog',
        ),
    ]
